<a href="https://colab.research.google.com/github/khairihr/MachineLearning/blob/main/Final%20Exam/00_pytorch_fundamentals_exercises_Khairi_Hibatullah_Ridho_1103228240.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nama: Khairi Hibatullah Ridho

NIM: 1103228240

Final Exam

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [6]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [7]:
# Import torch
import torch

# Create random tensor
X = torch.rand(size=(7, 7))
X, X.shape

(tensor([[0.2645, 0.1237, 0.6802, 0.7697, 0.3226, 0.6680, 0.0628],
         [0.3645, 0.7883, 0.7203, 0.6069, 0.0512, 0.9454, 0.4688],
         [0.8986, 0.4829, 0.0070, 0.2646, 0.9529, 0.8823, 0.4164],
         [0.6024, 0.0212, 0.0288, 0.3825, 0.6916, 0.4038, 0.3868],
         [0.7403, 0.9434, 0.4953, 0.4344, 0.9732, 0.8024, 0.1586],
         [0.8798, 0.2606, 0.8396, 0.6635, 0.5643, 0.1180, 0.6507],
         [0.0235, 0.9861, 0.7157, 0.4208, 0.9748, 0.9480, 0.8927]]),
 torch.Size([7, 7]))

2. **Membuat Tensor Acak dengan Bentuk (7, 7)**:
   - Kode ini mengimpor pustaka PyTorch.
   - Kemudian, kode membuat sebuah tensor acak dengan ukuran 7x7.
   - Setelah itu, kode menampilkan tensor tersebut dan ukurannya.

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [8]:
# Create another random tensor
Y = torch.rand(size=(1, 7))
# Z = torch.matmul(X, Y) # will error because of shape issues
Z = torch.matmul(X, Y.T) # no error because of transpose
Z, Z.shape

(tensor([[1.7836],
         [1.9781],
         [2.0625],
         [1.5516],
         [2.4743],
         [2.6463],
         [2.5490]]),
 torch.Size([7, 1]))

3. **Melakukan Perkalian Matriks pada Tensor**:
   - Kode ini membuat tensor acak lainnya dengan bentuk (1, 7).
   - Lalu, kode melakukan perkalian matriks antara tensor `X` dan transposisi dari tensor `Y`. Transposisi diperlukan agar dimensi tensor cocok untuk perkalian matriks.
   - Hasil dan ukuran hasil perkalian matriks ditampilkan.

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [9]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

4. **Mengatur Seed Acak dan Mengulang Langkah 2 & 3**:
   - Kode mengatur seed acak menjadi 0 untuk memastikan hasil yang konsisten pada setiap eksekusi.
   - Langkah-langkah membuat tensor dan melakukan perkalian matriks diulangi dengan seed yang telah ditetapkan.

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [10]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

5. **Mengatur Seed Acak pada GPU**:
   - Kode ini menunjukkan cara mengatur seed acak untuk operasi yang dilakukan pada GPU dengan menggunakan `torch.cuda.manual_seed()`.


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [11]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

6. **Membuat Dua Tensor Acak dan Mengirimnya ke GPU**:
   - Kode ini mengatur seed acak dan memeriksa ketersediaan GPU.
   - Dua tensor acak dibuat dan dikirim ke GPU. Ini memanfaatkan kemampuan komputasi GPU untuk operasi tensor.


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [12]:
# Perform matmul on tensor_A and tensor_B
# tensor_C = torch.matmul(tensor_A, tensor_B) # won't work because of shape error
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

7. **Melakukan Perkalian Matriks pada Tensor di GPU**:
   - Kode ini melakukan perkalian matriks pada dua tensor yang telah dibuat sebelumnya di GPU.
   - Untuk melakukan perkalian matriks, salah satu tensor harus di-transpose agar bentuknya cocok.

### 8. Find the maximum and minimum values of the output of 7.

In [13]:
# Find max
max = torch.max(tensor_C)

# Find min
min = torch.min(tensor_C)
max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

8. **Mencari Nilai Maksimum dan Minimum dari Hasil Perkalian Matriks**:
   - Kode ini mencari nilai maksimum dan minimum dari tensor hasil perkalian matriks.

### 9. Find the maximum and minimum index values of the output of 7.

In [14]:
# Find arg max
arg_max = torch.argmax(tensor_C)

# Find arg min
arg_min = torch.argmin(tensor_C)
arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


9. **Mencari Indeks Nilai Maksimum dan Minimum dari Hasil Perkalian Matriks**:
   - Kode ini menentukan indeks dari nilai maksimum (arg max) dan minimum (arg min) pada tensor hasil perkalian matriks.


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [15]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])


10. **Membuat Tensor Acak dan Menghilangkan Dimensi 1**:
   - Kode ini mengatur seed acak menjadi 7, membuat tensor acak dengan bentuk (1, 1, 1, 10), dan kemudian menghilangkan semua dimensi yang berukuran 1 (menggunakan metode `.squeeze()`), sehingga menghasilkan tensor dengan bentuk (10).
   - Tensor asli dan tensor hasil `.squeeze()` beserta bentuknya ditampilkan.